name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # <-- Здесь имя вашей основной ветки

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # <-- Версия Node.js, если нужна
          
      - name: Install Dependencies
        run: npm ci # <-- Команда для установки зависимостей
          
      - name: Build Project
        run: npm run build # <-- Команда для сборки проекта
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # <-- ПАПКА, КУДА СОБИРАЕТСЯ ПРОЕКТ (у вас может быть 'build')
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4